# Generated by Django 5.0.1 on 2024-02-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='forgot_password_token',
            new_name='forget_password_token',
        ),
    ]
