# Generated by Django 5.0.1 on 2024-02-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Extra_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Other_Ammenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Safety_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Hotel', 'Hotel'), ('Tent', 'Tent'), ('Guest_House', 'Guest House'), ('Bed_and_Breakfast', 'Beds and Breakfast'), ('HomeStay', 'HomeStay'), ('Cabin', 'Cabin')], max_length=20)),
                ('guest_room', models.CharField(choices=[('entire_place', 'Entire Place'), ('a_room', 'A Room'), ('shared_room', 'Shared Room')], max_length=20)),
                ('guest_bathroom', models.CharField(choices=[('private_bathroom', 'Private and Attached'), ('dedicated_bathroom', 'Dedicated'), ('shared_bathroom', 'Shared')], max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('ammenities', models.ManyToManyField(to='property.ammenities')),
                ('extra_items', models.ManyToManyField(to='property.extra_items')),
                ('other_ammenities', models.ManyToManyField(to='property.other_ammenities')),
                ('safety_items', models.ManyToManyField(to='property.safety_items')),
            ],
        ),
    ]
