# Generated by Django 5.0.1 on 2024-03-31 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ammenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extra_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Other_Ammenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Safety_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(blank=True, choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Hotel', 'Hotel'), ('Tent', 'Tent'), ('Guest_House', 'Guest House'), ('Bed_and_Breakfast', 'Beds and Breakfast'), ('HomeStay', 'HomeStay'), ('Cabin', 'Cabin')], default=None, max_length=20, null=True)),
                ('guest_room', models.CharField(blank=True, choices=[('entire_place', 'Entire Place'), ('a_room', 'A Room'), ('shared_room', 'Shared Room')], default=None, max_length=20, null=True)),
                ('Guest_number', models.IntegerField(default=None, null=True)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bed', models.IntegerField(default=1)),
                ('guest_bathroom', models.CharField(blank=True, choices=[('private_bathroom', 'Private and Attached'), ('dedicated_bathroom', 'Dedicated'), ('shared_bathroom', 'Shared')], default=None, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('ammenities', models.ManyToManyField(to='property.ammenities')),
                ('extra_items', models.ManyToManyField(to='property.extra_items')),
                ('other_ammenities', models.ManyToManyField(to='property.other_ammenities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('safety_items', models.ManyToManyField(to='property.safety_items')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_days', models.IntegerField()),
                ('num_guests', models.IntegerField()),
                ('before_service_fee', models.IntegerField()),
                ('service_fee', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Property_Photos')),
                ('property_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_photo', to='property.propertyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, max_length=255)),
                ('rating', models.FloatField()),
                ('status', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertyinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
