# Generated by Django 5.0.1 on 2024-03-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Extra_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Other_Ammenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Safety_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(blank=True, choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Hotel', 'Hotel'), ('Tent', 'Tent'), ('Guest_House', 'Guest House'), ('Bed_and_Breakfast', 'Beds and Breakfast'), ('HomeStay', 'HomeStay'), ('Cabin', 'Cabin')], default=None, max_length=20, null=True)),
                ('guest_room', models.CharField(blank=True, choices=[('entire_place', 'Entire Place'), ('a_room', 'A Room'), ('shared_room', 'Shared Room')], default=None, max_length=20, null=True)),
                ('Guest_number', models.IntegerField(default=None, null=True)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bed', models.IntegerField(default=1)),
                ('guest_bathroom', models.CharField(blank=True, choices=[('private_bathroom', 'Private and Attached'), ('dedicated_bathroom', 'Dedicated'), ('shared_bathroom', 'Shared')], default=None, max_length=20, null=True)),
                ('images', models.ImageField(blank=True, upload_to='images/Photo')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('ammenities', models.ManyToManyField(to='property.ammenities')),
                ('extra_items', models.ManyToManyField(to='property.extra_items')),
                ('other_ammenities', models.ManyToManyField(to='property.other_ammenities')),
                ('safety_items', models.ManyToManyField(to='property.safety_items')),
            ],
        ),
    ]
