# Generated by Django 5.0.1 on 2024-02-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='Guest_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='bed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/Photo'),
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='guest_bathroom',
            field=models.CharField(choices=[('private_bathroom', 'Private and Attached'), ('dedicated_bathroom', 'Dedicated'), ('shared_bathroom', 'Shared')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='guest_room',
            field=models.CharField(choices=[('entire_place', 'Entire Place'), ('a_room', 'A Room'), ('shared_room', 'Shared Room')], default=None, max_length=20),
        ),
    ]
