# Generated by Django 5.0.1 on 2024-03-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyinfo',
            name='images',
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='PropertyPhoto',
            field=models.ImageField(blank=True, upload_to='Photo'),
        ),
    ]
