# Generated by Django 5.0.1 on 2024-03-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_propertyinfo_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammenities',
            name='name',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
