# Generated by Django 5.0.1 on 2024-02-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertyinfo_guest_number_propertyinfo_bed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='Guest_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
