# Generated by Django 5.0.1 on 2024-02-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_propertyinfo_guest_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Hotel', 'Hotel'), ('Tent', 'Tent'), ('Guest_House', 'Guest House'), ('Bed_and_Breakfast', 'Beds and Breakfast'), ('HomeStay', 'HomeStay'), ('Cabin', 'Cabin')], default='House', max_length=20),
        ),
    ]
