# Generated by Django 5.0.1 on 2024-04-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='booked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='reserved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
