# Generated by Django 5.0.1 on 2024-03-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_ammenities_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_items',
            name='name',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='other_ammenities',
            name='name',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='safety_items',
            name='name',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
