# Generated by Django 5.0.1 on 2024-04-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_propertyinfo_booked_propertyinfo_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='guest_room',
            field=models.CharField(blank=True, choices=[('Entire Place', 'Entire Place'), ('Single Room', 'A Room'), ('Shared Room', 'Shared Room')], default=None, max_length=20, null=True),
        ),
    ]
