# Generated by Django 5.0.1 on 2024-02-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_propertyinfo_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='property_type',
            field=models.CharField(blank=True, choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Hotel', 'Hotel'), ('Tent', 'Tent'), ('Guest_House', 'Guest House'), ('Bed_and_Breakfast', 'Beds and Breakfast'), ('HomeStay', 'HomeStay'), ('Cabin', 'Cabin')], default=None, max_length=20, null=True),
        ),
    ]
