# Generated by Django 5.0.1 on 2024-04-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_propertyinfo_guest_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='property_type',
            field=models.CharField(blank=True, choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Hotel', 'Hotel'), ('Tent', 'Tent'), ('Guest House', 'Guest House'), ('Bed and Breakfast', 'Beds and Breakfast'), ('Homestay', 'HomeStay'), ('Cabin', 'Cabin')], default=None, max_length=20, null=True),
        ),
    ]
