# Generated by Django 5.0.1 on 2024-04-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_propertyinfo_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyinfo',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='propertyinfo',
            name='reserved',
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='guest_room',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Reserved', 'Reserved')], default=None, max_length=20, null=True),
        ),
    ]
