# Generated by Django 5.0.1 on 2024-04-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_remove_propertyinfo_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='Status',
            field=models.CharField(choices=[('Listing', 'Listing'), ('Booked', 'Booked'), ('Reserved', 'Reserved')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='guest_room',
            field=models.CharField(blank=True, choices=[('Entire Place', 'Entire Place'), ('Single Room', 'A Room'), ('Shared Room', 'Shared Room')], default=None, max_length=20, null=True),
        ),
    ]
