# Generated by Django 5.0.1 on 2024-02-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_propertyinfo_guest_bathroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
