# Generated by Django 5.0.1 on 2024-02-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_propertyinfo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
