# Generated by Django 5.0.1 on 2024-04-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_propertyinfo_status_alter_propertyinfo_guest_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='Booking_Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default='Pending', max_length=20),
        ),
    ]
