# Generated by Django 5.0.1 on 2024-04-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_propertyinfo_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='Booking_Status',
            field=models.CharField(choices=[('Listing', 'Listing'), ('Booked', 'Booked'), ('Reserved', 'Reserved')], default=None, max_length=20),
        ),
    ]
