# Generated by Django 5.0.1 on 2024-02-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_propertyinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
