# Generated by Django 5.0.1 on 2024-02-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_propertyinfo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammenities',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='extra_items',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='other_ammenities',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='safety_items',
            name='name',
            field=models.CharField(max_length=225),
        ),
    ]
