# Generated by Django 5.0.1 on 2024-04-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_propertyinfo_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyinfo',
            name='Booking_Status',
        ),
        migrations.RemoveField(
            model_name='propertyinfo',
            name='Guest_number',
        ),
        migrations.RemoveField(
            model_name='propertyinfo',
            name='Status',
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='booking_status',
            field=models.CharField(choices=[('Listing', 'Listing'), ('Booked', 'Booked'), ('Reserved', 'Reserved')], default='Listing', max_length=20),
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='guest_number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='propertyinfo',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default='Pending', max_length=20),
        ),
    ]
