# Generated by Django 5.0.1 on 2024-04-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_remove_propertyinfo_booking_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyinfo',
            old_name='booking_status',
            new_name='Booking_Status',
        ),
        migrations.RenameField(
            model_name='propertyinfo',
            old_name='guest_number',
            new_name='Guest_number',
        ),
        migrations.RenameField(
            model_name='propertyinfo',
            old_name='status',
            new_name='Status',
        ),
    ]
