# Generated by Django 5.0.1 on 2024-04-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_rename_booking_status_propertyinfo_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
